### ISSUE TITLE
Dashboard problem

### ISSUE THREAD

**Issue by ju52b** [peterhanania/Pogy#28]
hello Peter,

I m using the pogy bot code and i have a problem, when i go to the dashboard and go to report or contact and send a message, it tell me in the console :
```
(node:6915) UnhandledPromiseRejectionWarning: DiscordAPIError: 404: Not Found
    at RequestHandler.execute (/home/runner/MoonLobby/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/MoonLobby/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:6915) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and i hope you tell me how to fix it

Regards,
Ju52b

**Comment by gabgabmartin** [comment]
Hello!

I'm gabgabmartin and I am using the Pogy's Code too.

Did you fill up all the info on config.js and config.json?

**Comment by ju52b** [comment]
i did replace the webhook URL and id from the config
