### ISSUE TITLE
TypeError: Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by yashmehla** [peterhanania/Pogy#34]
TypeError: Cannot read property 'members' of undefined
    at /home/runner/Bot-with-Advanced-Dashboard/dashboard/dashboard.js:640:25
    at Layer.handle [as handle_request] (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/route.js:137:13)
    at checkAuth (/home/runner/Bot-with-Advanced-Dashboard/dashboard/dashboard.js:138:41)
    at Layer.handle [as handle_request] (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/runner/Bot-with-Advanced-Dashboard/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:317:13)
    at /home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/runner/Bot-with-Advanced-Dashboard/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:317:13)
    at /home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/Bot-with-Advanced-Dashboard/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/home/runner/Bot-with-Advanced-Dashboard/node_modules/passport/lib/middleware/authenticate.js:343:9)
    at /home/runner/Bot-with-Advanced-Dashboard/node_modules/passport/lib/strategies/session.js:69:12
    at pass (/home/runner/Bot-with-Advanced-Dashboard/node_modules/passport/lib/authenticator.js:337:31)
    at deserialized (/home/runner/Bot-with-Advanced-Dashboard/node_modules/passport/lib/authenticator.js:349:7)
    at /home/runner/Bot-with-Advanced-Dashboard/dashboard/dashboard.js:76:45

**Comment by AhmadShkour71** [comment]
see pins in support channel in support guild
