### ISSUE TITLE
SyntaxError: /home/runner/Pogy/config.json: Unexpected token / in JSON at position 44

### ISSUE THREAD

**Issue by Hardikanand1st** [peterhanania/Pogy#37]
 node shard.js
internal/modules/cjs/loader.js:1044
    throw err;
    ^

SyntaxError: /home/runner/Pogy/config.json: Unexpected token / in JSON at position 44
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Pogy/shard.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
exit status 1

**Comment by xptea** [comment]
I am having the same problem

**Comment by AhmadShkour71** [comment]
@xptea  @Hardikanand1st 

Learning Javascript for fix this
it is so basically

**Comment by Hardikanand1st** [comment]
Come on  just please tell how to fix

**Comment by peterhanania** [comment]
Learn how to use JSONs 🙂

**Comment by GGLVXD** [comment]
this shit aint helpfull :/
