### ISSUE TITLE
Cannot read property 'tag' of undefined

### ISSUE THREAD

**Issue by Khaled-Waqqas** [peterhanania/Pogy#5]
this error show me but not every time
idk what that

```js
(node:366) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tag' of undefined
    at Timeout._onTimeout (/home/runner/bottext/events/ready.js:187:124)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:366) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by peterhanania** [comment]
ready.js line 187? Are you using your own bot? or Pogy?

**Comment by Khaled-Waqqas** [comment]
> ready.js line 187? Are you using your own bot? or Pogy?

own bot,but iam dont change anything
idk why
in pogy you see this error?

**Comment by peterhanania** [comment]
hm, this error isn't from pogy then. Join the support server and open a ticket (https://pogy.xyz/support) for further assistance.
